name: Deploy static content to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: "sh -c 'wget \"https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_SHA}.zip\" -O artifact.zip'"
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: github-pages
          path: 'artifact.zip'
          retention-days: 1
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
